programa/programa/estado/urls.py
from django.urls import path
from . import views

urlpatterns = [
    ##               nome funcao                chamada interna
    path('inserirEstado/', views.insert_tel, name="insert_estado"),
    path('listarEstado/', views.list_tel, name="list_estado"),
]

programa/programa/programa/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('pessoa/', include('pessoa.urls')),
    path('admin/', admin.site.urls),
#  path('estado/', include('estado.urls')),
]

programa/programa/estado/models.py
from django.db import models

# Create your models here.

class EstadoModel(models.Model):
    estado_id = models.AutoField(primary_key=True)
    estado_nome = models.CharField(
        max_length=15,
        null=False,
        blank=False,
        verbose_name="Nome")
    estado_sigla = models.CharField(
        max_length=15,
        null=False,
        blank=False,
        verbose_name="Sigla")

    class Meta:
        ordering = ['estado_nome']
        verbose_name = 'estado'
        verbose_name_plural = 'Estados'

    def __str__(self):
        return self.estado_sigla


class CidadeModel(models.Model):
    cidade_id = models.AutoField(primary_key=True)
    cidade_nome = models.CharField(
        max_length=15,
        null=False,
        blank=False,
        verbose_name="Cidade")
    estado = models.ForeignKey(EstadoModel, on_delete=models.CASCADE, null=True,blank=True)

programa/programa/estado/forms.py
from django import forms
from .models import EstadoModel
from .models import CidadeModel

class EstadoForm(forms.ModelForm):
    estado_nome = forms.CharField(label="Nome")
    estado_sigla = forms.CharField(label="Sigla")

    class Meta:
        model = EstadoModel
        fields = [
            'estado_nome',
            'estado_sigla'
        ]

class CidadeForm(forms.ModelForm):
    cidade_nome = forms.CharField(label="Cidade")
    cidade_estado = forms.ModelChoiceField(queryset=EstadoModel.objects.all(), label="estado")

    class Meta:
        model = CidadeModel
        fields = [
            'cidade_nome',
            'cidade_estado'
        ]

programa/programa/pessoa/forms.py
from django import forms
from .models import PessoaModel
from .models import ContatoModel
from .models import EstadoModel
from .models import CidadeModel

class PessoaForm(forms.ModelForm):
    pessoa_nome = forms.CharField(required=True, label="Nome")
    pessoa_logradouro = forms.CharField(required=True,label="Logradouro")
    pessoa_numero = forms.CharField(required=True,label="Número")

    class Meta:
        model = PessoaModel
        fields = [
            'pessoa_nome',
            'pessoa_logradouro',
            'pessoa_numero',
        ]



class ContatoForm(forms.ModelForm):
    contato_telefone = forms.CharField(label="Telefone")
    contato_pessoa = forms.ModelChoiceField(queryset=PessoaModel.objects.all(), label="Contato")

    class Meta:
        model = ContatoModel
        fields = [
            'contato_telefone',
            'contato_pessoa'
        ]

class EstadoForm(forms.ModelForm):
    estado_nome = forms.CharField(label="Nome")
    estado_sigla = forms.CharField(label="Sigla")

    class Meta:
        model = EstadoModel
        fields = [
            'estado_nome',
            'estado_sigla'
        ]

class CidadeForm(forms.ModelForm):
    cidade_nome = forms.CharField(label="Cidade")
    cidade_estado = forms.ModelChoiceField(queryset=EstadoModel.objects.all(), label="estado")

    class Meta:
        model = CidadeModel
        fields = [
            'cidade_nome',
            'cidade_estado'
        ]

programa/programa/estado/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from.models import CidadeForm
from.forms import EstadoForm
from.models import EstadoModel
from.models import CidadeModel

# Create your views here.
#
# def update_pessoa(request, id):
#     pessoa = get_object_or_404(PessoaModel, pessoa_id=id)
#     form = PessoaForm(request.POST or None, instance=pessoa)
#     if form.is_valid():
#         form.save()
#         return redirect('list_pessoa')
#     context = {
#         'form':form
#     }
#     return render(request,'novo2.html', context)
#
#
# def delete_pessoa(request, id):
#     pessoa = get_object_or_404(PessoaModel, pessoa_id=id)
#     form = PessoaForm(request.POST or None, instance=pessoa)
#     if request.method == 'POST':
#         form.delete()
#         return redirect('list_pessoa')
#     context = {
#         'form':form
#     }
#     return render(request,'delete.html', context)


def list_estado(request):
    form = EstadoModel.objects.all()
    context = {
        'form':form,
    }
    return render(request, 'listarEstado.html', context)


def insert_estado(request):
    form = EstadoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('list_estado')
    context = {
        'form':form
    }
    return render(request, 'novoEstado.html', context)

programa/programa/estado/templates/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div>
            <table class="table table-striped table-bordered table-hover table-collapse">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Logradouro</th>
                        <th>Numero</th>
						<th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                {%for p in form%}
                 <tr>
                     <td>{{p.pessoa_nome}}</td>
                     <td>{{p.pessoa_logradouro}}</td>
                     <td>{{p.pessoa_numero}}</td>
					 <td class="text-center">						
						<a id="idAlterar" class="btn btn-warning btn-sm" href="{%url 'update_pessoa' p.pessoa_id%}">Alterar</a>		
						<a id="idExcluir" class="btn btn-danger btn-sm" href="{%url 'delete_pessoa' p.pessoa_id%}">Exluir</a>
					 </td>
                 </tr>
                {%endfor%}
                </tbody>
            </table>
			<a id="idIncluir" class="btn btn-primary btn-md" href="{%url 'insert_pessoa'%}">Novo</a>
        </div>

    </div>

</body>
</html>

programa/programa/estado/templates/listarEstado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div>
            <table class="table table-striped table-bordered table-hover table-collapse">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Sigla</th>
						<th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                {%for t in form%}
                 <tr>
                     <td>{{t.estado_nome}}</td>
                     <td>{{t.estado_sigla}}</td>
                     <td class="text-center">
						<a id="idAlterar" class="btn btn-warning btn-sm" href="{}">Alterar</a>
						<a id="idExcluir" class="btn btn-danger btn-sm" href="{}">Exluir</a>
					 </td>

                 </tr>
                {%endfor%}
                </tbody>
            </table>
			<a id="idIncluir" class="btn btn-primary btn-md" href="{%url 'insert_estado'%}">Novo</a>
        </div>

    </div>

</body>
</html>

programa/programa/estado/templates/listarTel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div>
            <table class="table table-striped table-bordered table-hover table-collapse">
                <thead>
                    <tr>
                        <th>Numero</th>
                        <th>Pessoa</th>
						<th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                {%for t in form%}
                 <tr>
                     <td>{{t.contato_telefone}}</td>
                     <td>{{t.pessoa}}</td>
                     <td class="text-center">
						<a id="idAlterar" class="btn btn-warning btn-sm" href="{}">Alterar</a>
						<a id="idExcluir" class="btn btn-danger btn-sm" href="{}">Exluir</a>
					 </td>

                 </tr>
                {%endfor%}
                </tbody>
            </table>
			<a id="idIncluir" class="btn btn-primary btn-md" href="{%url 'insert_tel'%}">Novo</a>
        </div>

    </div>

</body>
</html>

programa/programa/estado/templates/novo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro de pessoa</title>
</head>
<body>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>

</body>
</html>

programa/programa/estado/templates/novo1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro de pessoa</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="container">
    <div class="jumbotron">

        <div class="page-header text-center">
            <h2>Cadastro</h2>
        </div>

        <form class="form-horizontal" role="form" method="POST">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="" for="pessoa_nome">Nome</label>
                        <input id="pessoa_nome" type="text" name="pessoa_nome" value="{{pessoa_nome}}" class="form-control"/>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-1 text-center">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>

        </form>
    </div>
</body>
</html>

programa/programa/estado/templates/novo2.html
{% extends "base.html" %}

{%load bootstrap%}

{%block main%}
   <form class="form-horizontal" role="form" method="post" >
       {%csrf_token%}
       <!--{{form|bootstrap}}-->
       {{form|bootstrap_horizontal:'col-sm-1'}}
       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>
{%endblock%}

programa/programa/estado/templates/novo3.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}

<form class="form-horizontal" role="form" method="post" >
       {%csrf_token%}

		<h1>Esse é o novo3</h1>
       <div class="row">
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_pessoa_nome"
	                 class="col-sm-2 control-label">{{form.pessoa_nome.label}}</label>
	                 {% render_field form.pessoa_nome class='form-control'%}
	                 {% for error in form.pessoa_nome.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_pessoa_logradouro"
	                 class="col-sm-2 control-label">{{form.pessoa_logradouro.label}}</label>
	                 {% render_field form.pessoa_logradouro class='form-control'%}
	                 {% for error in form.pessoa_logradouro.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
		   <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_pessoa_logradouro"
	                 class="col-sm-2 control-label">{{form.pessoa_numero.label}}</label>
	                 {% render_field form.pessoa_numero class='form-control'%}
	                 {% for error in form.pessoa_numero.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
       </div>


       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>

{%endblock%}

programa/programa/estado/templates/novoEstado.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}

<form class="form-horizontal" role="form" method="post">
       {%csrf_token%}
		<h1>CADASTRO DE ESTADO</h1>
       <div class="row">
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="estado_nome"
	                 class="col-sm-2 control-label">{{form.estado_nome.label}}</label>
	                 {% render_field form.estado_nome class='form-control'%}
	                 {% for error in form.estado_nome.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
		   <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="estado_sigla"
	                 class="col-sm-2 control-label">{{form.estado_sigla.label}}</label>
	                  {% render_field form.estado_sigla class='form-control'%}
				  	  {% for error in form.estado_sigla.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
       </div>


       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>

{%endblock%}

programa/programa/estado/templates/novoTel.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}

<form class="form-horizontal" role="form" method="post">
       {%csrf_token%}

       <div class="row">
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="contato_telefone"
	                 class="col-sm-2 control-label">{{form.contato_telefone.label}}</label>
	                 {% render_field form.contato_telefone class='form-control'%}
	                 {% for error in form.contato_telefone.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
		   <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="pessoa"
	                 class="col-sm-2 control-label">{{form.pessoa.label}}</label>
	                  {% render_field form.contato_pessoa class='form-control'%}
				  	  {% for error in form.contato_pessoa.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>
       </div>


       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>

{%endblock%}